services:
  airport:
    build:
      context: .
    container_name: airport_service
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8001:8000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: airport_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
